doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    # Specify the correct server version if using MySQL. Update '8.0' based on your MySQL version.
    server_version: "8.0" # Adjust this based on your MySQL version
    profiling_collect_backtrace: "%kernel.debug%"
    use_savepoints: true

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    identity_generation_preferences:
      Doctrine\DBAL\Platforms\MySQLPlatform: identity # Changed to MySQL platform for clarity
    auto_mapping: true
    mappings:
      App:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
    controller_resolver:
      auto_mapping: false
