services:
  api:
    container_name: api_rubix
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_ENV=dev
    command: sh /var/www/html/watch.sh
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: server_nginx
    ports:
      - "8080:80" # Mapeia a porta 8080 do host para a porta 80 do contêiner
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Configuração do Nginx
    depends_on:
      - api
    restart: always
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: api_rubix_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rubixapi
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
