parameters:
  model_path: "%kernel.project_dir%/models-ml" # Path where your model files are stored

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Explicitly configure HealthService and QaService to use the model path
  App\Service\HealthService:
    arguments:
      $modelPath: "%model_path%"

  App\Service\QaService:
    arguments:
      $modelPath: "%model_path%"
