parameters:
  model_path: "%kernel.project_dir%/models-ml" # Caminho onde seus arquivos de modelo estão armazenados

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Controller\Connection\DatabaseConnectionController:
    tags: ["controller.service_arguments"]

  App\Service\QaService:
    arguments:
      $modelPath: "%kernel.project_dir%/models/latest_model.rbx" # Ajuste o caminho conforme necessário
